name: PerfectWiFi
favicon: null
layout_spectrum: 0.9127857820130885
typography_spectrum: 0.3715575358364731
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6153211714699864
  lightness: 0.6754569006152451
  saturation: 0.588219823082909
  rhythmicContrast: 0.5690255898516625
purpose: []
